Homework 2
================
Jinghao Zhang
2026-10-07

## Problem 1

``` r
nyc_transit =
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = recode_values(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset includes line, station name, latitude and longitude,
routes, entry, vending, entrance type, and ADA. I selected the variables
needed for the analysis, and converted `entry` from YES/NO to
TRUE/FALSE. The cleaned dataset has 1868 rows and 19 columns. The data
are not tidy because the routes are stored in multiple columns.

``` r
nyc_transit |>
  distinct(line, station_name)
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ℹ 455 more rows

``` r
nyc_transit |>
  filter(ada == TRUE) |>
  distinct(line, station_name)
```

    ## # A tibble: 84 × 2
    ##    line            station_name                  
    ##    <chr>           <chr>                         
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr      
    ##  2 4 Avenue        DeKalb Av                     
    ##  3 4 Avenue        Pacific St                    
    ##  4 42nd St Shuttle Grand Central                 
    ##  5 6 Avenue        34th St                       
    ##  6 6 Avenue        47-50th Sts Rockefeller Center
    ##  7 6 Avenue        Church Av                     
    ##  8 63rd Street     21st St                       
    ##  9 63rd Street     Lexington Av                  
    ## 10 63rd Street     Roosevelt Island              
    ## # ℹ 74 more rows

``` r
nyc_transit |>
  filter(vending == "NO") |>
  filter(entry == TRUE)
```

    ## # A tibble: 69 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 9th St                   40.7             -74.0 F      G      R     
    ##  2 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  3 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  4 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  5 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  6 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  7 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  8 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  9 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ## 10 6 Avenue Bergen St                40.7             -74.0 F      G      <NA>  
    ## # ℹ 59 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

proportion of station entrances / exits without vending allow entrance =
69/183 = 37.7%

``` r
nyc_transit_tidy = 
  nyc_transit |>
  mutate(
    across(route1:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name")

nyc_transit_tidy
```

    ## # A tibble: 20,548 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 10 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## # ℹ 20,538 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <chr>,
    ## #   route_name <chr>

``` r
nyc_transit_tidy |>
  filter(route_name == "A") |>
  distinct(line, station_name)
```

    ## # A tibble: 60 × 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # ℹ 50 more rows

there are 60 distinct stations.

``` r
nyc_transit_tidy |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name)
```

    ## # A tibble: 17 × 2
    ##    line             station_name                 
    ##    <chr>            <chr>                        
    ##  1 8 Avenue         14th St                      
    ##  2 8 Avenue         168th St - Washington Heights
    ##  3 8 Avenue         175th St                     
    ##  4 8 Avenue         34th St                      
    ##  5 8 Avenue         42nd St                      
    ##  6 8 Avenue         59th St                      
    ##  7 8 Avenue         Inwood - 207th St            
    ##  8 8 Avenue         West 4th St                  
    ##  9 8 Avenue         World Trade Center           
    ## 10 Broadway         Times Square-42nd St         
    ## 11 Broadway-7th Ave 59th St-Columbus Circle      
    ## 12 Broadway-7th Ave Times Square                 
    ## 13 Canarsie         8th Av                       
    ## 14 Franklin         Franklin Av                  
    ## 15 Fulton           Euclid Av                    
    ## 16 Fulton           Franklin Av                  
    ## 17 Rockaway         Howard Beach

17 stations are ADA compliant.

## Problem 2

``` r
mr_trash_wheel =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

professor_trash_wheel =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = cell_cols("A:M"),
    na = "dive"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  )

gwynnda =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = cell_cols("A:L")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynnda"
  )

trash_wheel_tidy =
  bind_rows(
    mr_trash_wheel,
    professor_trash_wheel,
    gwynnda
  )

trash_wheel_tidy
```

    ## # A tibble: 1,269 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,259 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

``` r
professor_total_weight =
  trash_wheel_tidy |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(total_weight = sum(weight_tons, na.rm = TRUE))

gwynnda_cigarette_butts =
  trash_wheel_tidy |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(total_butts = sum(cigarette_butts, na.rm = TRUE))

professor_total_weight
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         295.

``` r
gwynnda_cigarette_butts
```

    ## # A tibble: 1 × 1
    ##   total_butts
    ##         <dbl>
    ## 1       18120

The combined dataset contains 1,269 observations and 15 variables,
including key varibles like dumpster, month, year, and weight. Professor
Trash Wheel collected 295 tons of trash. 18,120 cigarette butts were
collected by Gwynnda in June 2022.
